services:
  - type: web
    name: gtuber-api
    env: python
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn backend:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
